config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'piece_of_arts#index'
  resources :piece_of_arts, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
    end
  resources :bookings, only: [:show, :index, :update]

  get '/user/', to: 'profiles#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :piece_of_art
  validates :start_date, presence: true, allow_blank: false
  validates :end_date, presence: true, allow_blank: false
end

app/models/piece_of_art.rb
class PieceOfArt < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :name, :category, :daily_price, :artist_name, presence: true

  include PgSearch::Model

  pg_search_scope :search_by_name_and_artist_name,
    against: [ :name, :artist_name ],
    using: {
      tsearch: { prefix: true }
    }

  # def check_for_availability(date)
  #   TODO
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :bookings
  has_many :piece_of_arts
  has_many :booked_poa, through: :piece_of_arts, source: :bookings

  has_one_attached :user_banner
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
 before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:address, :avatar, :banner,:username])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def index
    # "je suis un propriétaire qui a plusieurs oeuvre dart et je veux voir les bookings associé"
    # @owner_piece_of_arts = PieceOfArt.where(user_id: current_user)
    # @owner_allbookings = @piece_of_arts.map {|e| Booking.where(piece_of_art: e)}
    # @bookingspending = Bookings.where()
    @owner_bookings = current_user.booked_poa
    @owner_pending_bookings = current_user.booked_poa.map { |booking| booking if booking.status == 'pending'  }.compact
    @owner_approved_bookings = current_user.booked_poa.map { |booking| booking if booking.status == 'approved'  }.compact
    @owner_ongoing_bookings = current_user.booked_poa.map { |booking| booking if booking.status == 'ongoing'  }.compact
    @owner_past_bookings = current_user.booked_poa.map { |booking| booking if booking.status == 'terminated'  }.compact
    @owner_declined_bookings = current_user.booked_poa.map { |booking| booking if booking.status == 'declined'  }.compact


  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
  @user = current_user
  @booking = Booking.find(params[:id])
  @action = params[:Action]

  if @action == 'Approve'
    @booking.status = 'approved'
    @booking.save!
  elsif @action == 'Decline' || @action == 'Cancel'
    @booking.status = 'declined'
    @booking.save!
  end
  redirect_to request.referrer

  # redirect_to bookings_path

  #addevent listener en fonction du boutton je change le status en "confirmed" ou "cancelled"
  #formulaire avec un object booking avec un champ caché qui me met le status

  #   if booking.status = 'pending'
  #      status =
  #     on va cherche status (confirmed or canceled)
  #   elsif status = 'confirmed'
  #     on va chercher, review, rating
  #   end
  #   @booking = booking.find(params[:id])
  # end
  end

  def new
    @piece_of_art = PieceOfArt.find(params[:piece_of_art_id])
    @booking = Booking.new()

  end


  def create
    @booking = Booking.new(params_booking)
    @piece_of_art = PieceOfArt.find(params[:piece_of_art_id])
    @booking.piece_of_art_id = params[:piece_of_art_id]
    @booking.user_id = current_user.id
    if @booking.valid?
      @booking.status = 'pending'
      @booking.number_of_days = (@booking.end_date - @booking.start_date).to_i
      @booking.total_price = @booking.number_of_days * @booking.piece_of_art.daily_price
      @booking.save
      redirect_to user_path(current_user)
    else
      render :new
    end

  end


private

  def params_booking
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

end

app/controllers/piece_of_arts_controller.rb
class PieceOfArtsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home


  def index
    @piece_of_arts = PieceOfArt.all
    results = []

    if params[:query].present?
      words = params[:query].split(' ')

      words.each do |word|
        results << PieceOfArt.search_by_name_and_artist_name(word)
      end

      @piece_of_arts = PieceOfArt.where(id: results.map { |c| c.pluck(:id) }.flatten)
    end

    if params[:post] && params[:post][:categories].count > 1
      @piece_of_arts = @piece_of_arts.where(category: params[:post][:categories].reject(&:empty?))
    end


    # if params[:query].present?
    #   @piece_of_arts = PieceOfArt.where(name: params[:query])
    # else
    #   @piece_of_arts
    # end

    # afficher dans l'index seulement les categories presentent dans le catalogue
    @categories = @piece_of_arts.uniq do |poa|
      poa.category
    end
    # @piece_of_arts_filtered = PieceOfArt.find(params[:search]) #Doubt on hwo to write params here
  end

  def show
    @piece_of_art = PieceOfArt.find(params[:id])
  end

  def new
    @piece_of_art = PieceOfArt.new()
  end

  def create
    @piece_of_art = PieceOfArt.new(params_poa)
    @piece_of_art.user = current_user
    if @piece_of_art.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end



  private

  def params_poa
    params.require(:piece_of_art).permit(:name, :category, :daily_price, :description, :artist_name, :creation_date, :available_for_sale, :buying_price, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def show
  @user = current_user
  @piece_of_arts = @user.piece_of_arts
  @bookings = @user.bookings
    @pending_bookings = @user.bookings.where(status: 'pending')
    @approved_bookings = @user.bookings.where(status: 'approved')
    @ongoing_bookings = @user.bookings.where(status: 'ongoing' )
    @past_bookings = @user.bookings.where(status: 'terminated')
    @declined_bookings = @user.bookings.where(status: 'declined')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="show-poa-container">
  <div class="card-show-poa">
    <% if current_user.user_banner.attached? %>
      <div class="card-picture" style="background-image: url(<%= cl_image_path(current_user.user_banner.photo.key, height: 300, width: 400, crop: :fill) %>);">
      </div>
    <% else %>
      <div class="card-picture" style="background-image: url(<%= image_path('https://images.unsplash.com/photo-1555443805-658637491dd4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=932&q=80') %>);">
      </div>
    <% end %>


<% if @owner_pending_bookings.blank? && @owner_approved_bookings.blank? && @owner_ongoing_bookings.blank? && @owner_past_bookings.blank? && @owner_declined_bookings.blank? %>
<p> You have no booking history yet </p>
<% end %>

<% if @owner_pending_bookings.present? || @owner_approved_bookings.present? || @owner_ongoing_bookings.present? || @owner_past_bookings.present? || @owner_declined_bookings.present?  %>
<h1 class="light-h text-center"> My Dashboard </h1>
<% end %>

<% if @owner_pending_bookings.present? %>
  <h2 class="light-h text-center"> Pending my review </h2>


    <% @owner_pending_bookings.each do |booking| %>
    <div class="card-pro-poa  d-flex justify-content-between align-items-center">
       <div class="left-card d-flex">
          <% if booking.piece_of_art.photo.attached? %>
            <%= cl_image_tag booking.piece_of_art.photo.key %>
          <% end %>
        <div class="card-product-infos">
          <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
            <p>Start: <%= booking.start_date %></p>
            <p>End: <%= booking.end_date %></p>
            <p>Total Price:<%= booking.total_price%>€</p>
        </div>
      </div>

      <div class="right-card">
        <div class="status-buttons d-flex flex-column">
          <%= link_to 'Approve', booking_path(booking, params: { Action: 'Approve' }), method: :patch, class: 'btn btn-empty-poa mx-1  btn-navbar'  %>
          <%= link_to 'Decline', booking_path(booking, params: { Action: 'Decline' }), method: :patch, class: 'btn btn-empty-poa mx-1  btn-navbar'  %>
        </div>
      </div>
    </div>
    <% end %>

<% end %>

<% if @owner_approved_bookings.present? %>
  <h2 class="light-h text-center"> Accepted bookings </h2>

      <% @owner_approved_bookings.each do |booking| %>
      <div class="card-pro-poa  d-flex justify-content-between align-items-end">
        <div class="left-card d-flex">
          <% if booking.piece_of_art.photo.attached? %>
            <%= cl_image_tag booking.piece_of_art.photo.key %>
          <% end %>
          <div class="card-product-infos">
            <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
            <p>Start: <%= booking.start_date %></p>
            <p>End: <%= booking.end_date %></p>
            <p>Total Price:<%= booking.total_price%>€</p>
          </div>
        </div>

        <div class="right-card">
          <div class="status-buttons d-flex flex-column">
            <%= link_to 'Cancel', booking_path(booking, params: { Action: 'Cancel' }), method: :patch, class: 'btn btn-empty-poa mx-1 list-group-item btn-navbar'  %>
          </div>
        </div>
      </div>
      <% end %>

<% end %>

<% if @owner_ongoing_bookings.present? %>
  <h2 class="light-h text-center"> Currently Booked </h2>

    <% @owner_ongoing_bookings.each do |booking| %>
      <div class="card-pro-poa ">
        <% if booking.piece_of_art.photo.attached? %>
          <%= cl_image_tag booking.piece_of_art.photo.key %>
        <% end %>
        <div class="card-product-infos">
        <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
          <p>Start: <%= booking.start_date %></p>
          <p>End: <%= booking.end_date %></p>
          <p>Total Price:<%= booking.total_price%>€</p>
        </div>
      </div>
    <% end %>

<% end %>


  <% if @owner_past_bookings.present? %>
    <h2 class="light-h text-center"> Past Bookings </h2>

          <% @past_bookings.each do |booking| %>
            <div class="card-pro-poa ">
              <% if booking.piece_of_art.photo.attached? %>
                <%= cl_image_tag booking.piece_of_art.photo.key %>
              <% end %>
              <div class="card-product-infos">
                <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
                <p>Start: <%= booking.start_date %></p>
                <p>End: <%= booking.end_date %></p>
                <p>Total Price:<%= booking.total_price%>€</p>
                <h2><%= link_to 'Rate & review', booking_path(booking) %></h2>
              </div>
            </div>
          <% end %>

    <% end %>

  <% if @owner_declined_bookings.present? %>
    <h2 class="light-h text-center"> Booking Declined </h2>

      <% @owner_declined_bookings.each do |booking| %>
        <div class="card-pro-poa ">
          <% if booking.piece_of_art.photo.attached? %>
            <%= cl_image_tag booking.piece_of_art.photo.key %>
          <% end %>
          <div class="card-product-infos">
          <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
            <p>Start: <%= booking.start_date %></p>
            <p>End: <%= booking.end_date %></p>
            <p>Total Price:<%= booking.total_price%>€</p>
          </div>
        </div>
      <% end %>

  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="card-show-poa">
  <% if @piece_of_art.photo.attached? %>
    <div class="card-picture my-3" style="background-image: url(<%= cl_image_path(@piece_of_art.photo.key, height: 300, width: 400, crop: :fill) %>);">
    </div>
  <% else %>
    <div class="card-picture" style="background-image: url(<%= image_path('https://images.unsplash.com/photo-1555443805-658637491dd4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=932&q=80') %>);">
    </div>
  <% end %>

  <div class="card-description">
    <h1><%= @piece_of_art.name %> </h1>
    <h2><%= @piece_of_art.artist_name %> </h2>
    <div id="daily_price" data-price="<%= @piece_of_art.daily_price %>">
      <p>Daily price: <%= @piece_of_art.daily_price %> €</p>
    </div>
      <div class=" d-inline-flex">
        <%= simple_form_for [@piece_of_art, @booking], :html => { :class => 'form-inline' } do |f| %>
          <div class="input-group " id= "booking-input-form">
            <%= f.input :start_date, as: :string, label: false, placeholder: 'from' ,input_html: {class: "datepicker", id: "start_date"} %>
            <%= f.input :end_date, as: :string, label: false, placeholder: 'until', input_html: {class: "datepicker", id: "end_date"} %>
          </div>
        <%= f.button :submit, "Book now!", class: "btn btn-empty mt-3", id: "booking-submit-button" %>
        <% end %>
      </div>
          <div id="booking-cart">
            <div class="row mt-1">
              <p><%="Days: "%>&nbsp</p>
              <span id="number_of_days"></span>
            </div>
            <div class="row">
              <p><%="Total: "%>&nbsp</p>
              <span id="total_price"></span>
            </div>
          </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1, maximum-scale=1 shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
    <script src="https://unpkg.com/swiper/js/swiper.js" defer ></script>


    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/nav-bar' %>
    <% unless controller_name == 'piece_of_arts' && action_name == 'index' %>
     <div class="main-container" style='background-color: $main-color'>
    <% end %>
      <%= yield %>
    <% unless controller_name == 'piece_of_arts' && action_name == 'index' %>
    </div>
    <% end %>
    <div style="height: 100px;"></div>
      <%= render 'shared/footer' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<div class="row">
    <h1>Pages#home</h1>
    <h3>Les plus appréciés</h3>
    <%= render 'shared/swiper' %>
</div>
<div class="row">
    <h3>Les nouveautés</h3>
    <%= render 'shared/swiper' %>
</div>
<div class="row">
    <h3>Celles qui pourraient vous plaire </h3>
    <%= render 'shared/swiper' %>
</div>

app/views/piece_of_arts/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/piece_of_arts/index.html.erb
<%= render 'shared/banner-search' %>
<div class="below-banner-container">

  <div class="feed">
    <% if @piece_of_arts.count > 1 %>
        <p><%=@piece_of_arts.count%> pieces of art founded</p>
      <% elsif @piece_of_arts.count == 1 %>
        <p><%=@piece_of_arts.count%> piece of art founded</p>
      <% else %>
        <p>Sorry, we have nothing matching your criteria</p>
      <% end %>
    <% @piece_of_arts.each do |poa| %>
    <%= link_to piece_of_art_path(poa) do  %>
        <div class="carrousel-card">
        <div class="carrousel-img">
          <% if poa.photo.attached? %>
            <%= cl_image_tag poa.photo.key  %>
          <% end %>

        </div>
        <h3><%= poa.name %></h3>
        <h4><%= poa.artist_name %></h4>
        <div class="card-content">
          <p class="col-10"><%= poa.description %></p>
          <p class="price-in-card col-2"><%= poa.daily_price %>&nbsp€ /day</p>
        </div>
        </div>
      <% end %>
      <% end %>
  </div>

app/views/piece_of_arts/new.html.erb
<!-- formfor -->
<div class= "container" style="


background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),
url(https://images.unsplash.com/photo-1541367777708-7905fe3296c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2272&q=80);
color: white;
font-weight: bold;
justify-content: center;
">
  <div class= "form-group" >
    <%= simple_form_for @piece_of_art do |f| %>
      <%= f.input :name %>
      <%= f.input :category, :collection => %w[Painting Sculpture Photo] %>
      <%= f.input :daily_price, placeholder: 'euros', as: :integer %>
      <%= f.input :description, as: :text %>
      <%= f.input :artist_name %>
      <%= f.input :creation_date %>
      <%= f.input :available_for_sale, as: :boolean %>
      <%= f.input :buying_price, placeholder: 'euros', as: :integer %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit,:class => "btn btn-full mx-1 list-group-item btn-navbar" %>
        </div>
    <% end %>
  </div>
</div>

app/views/piece_of_arts/old_carrousel_TBE.html.erb
  <div class="row carrousel-title">
    <h3>Most wanted</h3>
  </div>
  <div class="row">
    <div class="swiper-container">
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
      <div class="swiper-wrapper">
        <% @piece_of_arts.each do |poa| %>
        <div class="swiper-slide">
          <div class="card-product mr-5">
            <% if poa.photo.attached? %>
              <%= cl_image_tag poa.photo.key %>
            <% end %>
            <div class="card-product-infos">
              <h2><%= link_to poa.name, piece_of_art_path(poa) %></h2>
              <p><%= poa.artist_name %></p>
              <p><%= poa.daily_price %> €</p>
            </div>
          </div>
        </div>
        <% end %>
    </div>
    </div>
  </div>
    <div class="row carrousel-title">
      <h3>Latest pieces</h3>
    </div>
    <div class="row">
      <div class="swiper-container">
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
          <div class="swiper-wrapper">
          <% @piece_of_arts.each do |poa| %>
          <div class="swiper-slide">
            <div class="card-product mr-5">
              <% if poa.photo.attached? %>
                <%= cl_image_tag poa.photo.key %>
              <% end %>
              <div class="card-product-infos">
                <h2><%= link_to poa.name, piece_of_art_path(poa) %></h2>
                <p><%= poa.artist_name %></p>
                <p><%= poa.daily_price%> €</p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/piece_of_arts/show.html.erb
<%#= render 'shared/banner-search' %>

<div class="show-poa-container">
  <div class="card-show-poa">
    <% if @piece_of_art.photo.attached? %>
      <div class="card-picture" style="background-image: url(<%= cl_image_path(@piece_of_art.photo.key, height: 300, width: 400, crop: :fill) %>);">
      </div>
    <% else %>
      <div class="card-picture" style="background-image: url(<%= image_path('https://images.unsplash.com/photo-1555443805-658637491dd4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=932&q=80') %>);">
      </div>
    <% end %>

    <div class="card-description">
      <h1><%= @piece_of_art.name %> </h1>
      <h2><%= @piece_of_art.artist_name %> </h2>
      <p>Category: <%= @piece_of_art.category %></p>
      <p>Description: <br><%= @piece_of_art.description %></p>
      <p>Daily price: <%=@piece_of_art.daily_price %> €</p>
      <% if @piece_of_art.available_for_sale == true %>
        <p>Available for Sale!</p>
        <p>Buying price :&nbsp<%= @piece_of_art.buying_price %></p>
      <% end %>
      <button name="button" type="submit" class="btn btn-empty" id="book-now-show-poa">
        <i class="fas fa-palette"> <%= link_to 'Book it!', new_piece_of_art_booking_path(@piece_of_art) %>
        </i>
      </button>
    </div>


  </div>
</div>

app/views/profiles/show.html.erb
<div class="show-poa-container">
  <div class="card-show-poa">
    <% if current_user.user_banner.attached? %>
      <div class="card-picture" style="background-image: url(<%= cl_image_path(current_user.user_banner.photo.key, height: 300, width: 400, crop: :fill) %>);">
      </div>
    <% else %>
      <div class="card-picture" style="background-image: url(<%= image_path('https://images.unsplash.com/photo-1555443805-658637491dd4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjF9&auto=format&fit=crop&w=932&q=80') %>);">
      </div>
    <% end %>


<% if @piece_of_arts.blank? && @pending_bookings.blank? && @approved_bookings.blank? && @ongoing_bookings.blank? && @past_bookings.blank? %>
<p> Your profile is currently empty, you can <%= link_to 'list a piece of Art', new_piece_of_art_path  %> or <%= link_to 'find one', piece_of_arts_path %> </p>
<% end %>

<% if @piece_of_arts.present? %>
<h2 class="light-h text-center" > My Piece of Arts </h2>

 <%  @piece_of_arts.each do |poa| %>
  <div class="card-pro-poa ">
    <% if poa.photo.attached? %>
      <%= cl_image_tag poa.photo.key %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= link_to poa.name, piece_of_art_path(poa) %></h2>
        <p>Artist: <%= poa.artist_name %></p>
        <p>Daily Price:<%= poa.daily_price%>€</p>
    </div>
  </div>
  <% end %>

<% end %>

<% if @pending_bookings.present? %>
<h2 class="light-h text-center justify-center"> Waiting for owner's approval </h3>

        <% @pending_bookings.each do |booking| %>
        <div class="card-pro-poa d-flex justify-content-between align-items-end">
          <div class="left-card d-flex">
            <% if booking.piece_of_art.photo.attached? %>
              <%= cl_image_tag booking.piece_of_art.photo.key %>
            <% end %>
            <div class="card-product-infos text-nowrap">
              <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
              <p>Start: <%= booking.start_date %></p>
              <p>End: <%= booking.end_date %></p>
              <p>Total Price:<%= booking.total_price%>€</p>
            </div>
          </div>

          <div class="right-card">
            <div class="status-buttons d-flex flex-column">
              <%= link_to 'Cancel', booking_path(booking, params: { Action: 'Cancel' }), method: :patch, class: 'btn btn-empty-poa mx-1 list-group-item btn-navbar'  %>
            </div>
          </div>
      </div>
      <% end %>
<% end %>

<% if @approved_bookings.present? %>
<h2 class="light-h text-center"> My next bookings </h2>

  <% @approved_bookings.each do |booking| %>
  <div class="card-pro-poa d-flex justify-content-between align-items-end">
          <div class="left-card d-flex">
            <% if booking.piece_of_art.photo.attached? %>
              <%= cl_image_tag booking.piece_of_art.photo.key %>
            <% end %>
            <div class="card-product-infos">
              <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
              <p>Start Date: <%= booking.start_date %></p>
              <p>End Date: <%= booking.end_date %></p>
              <p>Total Price:<%= booking.total_price%>€</p>
            </div>
          </div>

          <div class="right-card">
            <div class="status-buttons d-flex flex-column">
              <%= link_to 'Cancel', booking_path(booking, params: { Action: 'Cancel' }), method: :patch, class: 'btn btn-empty-poa mx-1 list-group-item btn-navbar'  %>
            </div>
          </div>
      </div>
  <% end %>

<% end %>

<% if @ongoing_bookings.present? %>
  <h2 class="light-h text-center"> Currently at Home </h2>

    <% @ongoing_bookings.each do |booking| %>
      <div class="card-pro-poa">
        <% if booking.piece_of_art.photo.attached? %>
          <%= cl_image_tag booking.piece_of_art.photo.key %>
        <% end %>
        <div class="card-product-infos">
          <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
          <p>Start Date: <%= booking.start_date %></p>
          <p>End Date: <%= booking.end_date %></p>
          <p>Total Price:<%= booking.total_price%>€</p>
        </div>
      </div>
    <% end %>

  <% end %>

  <% if @past_bookings.present? %>
    <h2 class="light-h text-center"> Past Bookings </h2>

      <% @past_bookings.each do |booking| %>
      <div class="card-pro-poa d-flex justify-content-between align-items-end">
          <div class="left-card d-flex">
            <% if booking.piece_of_art.photo.attached? %>
              <%= cl_image_tag booking.piece_of_art.photo.key %>
            <% end %>
            <div class="card-product-infos">
              <% if booking.piece_of_art.name.length > 16 %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% else %>
            <h2><%= booking.piece_of_art.name.first(14)+".." %></h2>
          <% end %>
              <p>Start Date: <%= booking.start_date %></p>
              <p>End Date: <%= booking.end_date %></p>
              <p>Total Price:<%= booking.total_price%>€</p>
            </div>
          </div>

          <div class="right-card">
            <div class="status-buttons d-flex flex-column">
              <%= link_to 'Review', booking_path(booking), method: :patch, class: 'btn btn-empty-poa mx-1 list-group-item btn-navbar'  %>
            </div>
          </div>
      </div>
       <% end %>

  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>